version: '2'
services:
  broker:
    build:
      context: ./radbroker
      dockerfile: Dockerfile
    ports:
      - "11812:1812/udp"
    depends_on: 
      - backend
      - redis
      - nats
  backend:
    build:
      context: ./radbackend
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    depends_on: 
      - redis
      - nats
  redis:
    image: redis:latest
    ports:
      - "16379:6379" # map port to none standard port, to avoid conflicts  
  nats:
    image: nats:latest
    ports:
      - "14222:4222" # map port to none standard port, to avoid conflicts 
  
